### ISSUE TITLE
Attribute missing in dropdown

### ISSUE THREAD

**Issue by git-seb** [Smile-SA/magento2-module-product-label#48] opened 2022-12-13 16:03 UTC
I've created a Yes/No attribute and added it to all attribute sets, reindexed and flushed cache but the attribute is not showing up in the dropdown to select as condition. Am I missing something here?

**Comment by git-seb** [comment] 2022-12-15 14:54
Found a work around by creating a new attribute with dropdown type instead of Yes/No type.

**Comment by cptX** [comment] 2023-03-09 20:46
I think you are referring to the same issue I opened just before you. Please read the existing issues before opening new ones...
https://github.com/Smile-SA/magento2-module-product-label/issues/40

**Comment by PierreGauthier** [comment] 2023-09-27 10:15
This is a duplicate of #31
It is fixed by eda380bc

**Closed by PierreGauthier** 2023-09-27 10:15 UTC
