### ISSUE TITLE
Attribute drop down list missing items

### ISSUE THREAD

**Issue by cptX** [Smile-SA/magento2-module-product-label#40] opened 2022-09-05 11:45 UTC
Hi, in magento 2.4.5:

If we create a "Product Attribute" as a Yes/No input type, the "Attribute" drop down list in the "New product label" creation page doesn't show it, so we cannot select it!
If we create a "Product Attribute" as a "Dropdown" with two options: "Yes" and "No" it will be available in the "Attribute" drop down list in the "New product label" creation page

Please check which Attribute types are shown and include as many as possible!

As an extra request that relates to the above problem I explain here another issue:

I would like a label "On Sale" to be automatically shown when a special price is set for a product!
I can create a product attribute "On Sale" and I can create a corresponding Product Label, but I need to enable the label manually for this product every time I set a special price. Is there a way to make the label show automatically if special price is available on the product?
If I try to create a new Product Label in the "Attribute" Dropdown list there is no option to make this relation. Could you implement this relation please? I consider this relevant with the above issue mentioned, as again the "Attribute" drop down doesn't give many options!

**Comment by PierreGauthier** [comment] 2023-09-27 10:16
This is a duplicate of #31
It is fixed by eda380bc

**Closed by PierreGauthier** 2023-09-27 10:16 UTC
